### ISSUE TITLE
ipv4-rules.sh line 33

### ISSUE THREAD

**Issue by Enkidu-6** [toralf/torutils#5]
Hi toralf,

Just wanted to mention that sort -u**n** doesn't play well with sorting IP addresses. The dot between the IP addresses throws it off and it will only sort digits before the first dot. To test it you can replace the snowflake address on that line with torproject.org and you'll see what I mean. You will only get 3 addresses instead of 5. I would remove the *n* and only use sort -u.

Thanks.

**Comment by toralf** [comment]
Umpf, thx for pointing to this, fix is in a472343

**Comment by Enkidu-6** [comment]
My pleasure.
