### ISSUE TITLE
ipv4-rules.sh line 118

### ISSUE THREAD

**Issue by Enkidu-6** [toralf/torutils#9]
Hi, 
I'm not sure if I'm confused by the script or I'm reading it right but it seems to me that you have a hashlimit burst of 1 for a tcp connection. That effectively means DROP the connection. A tcp connection consists of a SYN and an ACK and the system considers each one of them as --ctstate NEW. This means that with the burst limit of one, you accept the SYN but you drop the ACK because the limit is maxed out. So the connection never happens.

To test it set the hashlimit burst for port 443 to one and do a connect port scan with nmap 
```
nmap -sT -p443 ipaddress
```
and your port will show as filtered as opposed to open. A hashlimit of 2 allows one connection, 4 allows 2. 1 allows nothing.

Please forgive me if I didn't understand the script right.

**Comment by toralf** [comment]
The idea is to act on SYN packets only: ` local synpacket="iptables -A INPUT -p tcp --dst $orip --dport $orport --syn"`

> and your port will show as filtered as opposed to open. A hashlimit of 2 allows one connection, 4 allows 2. 1 allows nothing.

Erm, do you have a reference in the official doc stating this too ?

**Comment by Enkidu-6** [comment]
Don't have a reference handy but I just scanned your port 443 and it's filtered. I also put your relay as an EntryNode in my tor browser's torrc and it won't connect.

hashlimit is a double edged sword, I hate it but I use it too in my scripts. It doesn't just throttle your inbound connection, it also throttles your outbound connection because of the SYN/ACK dependence.

**Comment by toralf** [comment]
> Don't have a reference handy but I just scanned your port 443 and it's filtered. I also put your relay as an EntryNode in my tor browser's torrc and it won't connect.

The port is definitely open, but your scan attempt likely put your ip on my block list.
```
# ss -n -6 | grep ESTAB | grep -c -F ' [2a01:4f9:3b:468e::13]:443 '
941
# ss -n -4 | grep ESTAB | grep -c -F ' 65.21.94.13:443 '
5135
```

**Comment by Enkidu-6** [comment]
May be. However I scanned it using two different IP addresses and only once. One scan shouldn't put it on block list. Also my tor browser is on a different IP address on my laptop at home. Have you tried connecting to your relay as an EntryNode on a tor browser?

Here's a third scan from the third IP Address:
```
# nmap -sT -p443 65.21.94.13
Starting Nmap 7.70 ( https://nmap.org ) at 2023-01-04 21:57 UTC
Nmap scan report for tor-relay.zwiebeltoralf.de (65.21.94.13)
Host is up (0.023s latency).

PORT    STATE    SERVICE
443/tcp filtered https

Nmap done: 1 IP address (1 host up) scanned in 0.92 seconds
```

**Comment by toralf** [comment]
Both servers from https://metrics.torproject.org/rs.html#search/toralf do not show any problems, the lcoal stats show thousands of connected clients, so no problem at his end.
You can run
```
yes | openssl s_client -connect 65.21.94.13:443
yes | openssl s_client -connect 65.21.94.13:9001
```
to see that the connection is made.

**Comment by Enkidu-6** [comment]
Okay thanks. Sorry to bother you.
